[context.production]
  environment = { NODE_VERSION = "14.16.0" }
  [[headers]]
    for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      Referrer-Policy = "no-Referrer"
      Content-Security-Policy = "frame-ancestors 'none'"
      X-Content-Type-Options = "nosniff"
      Permissions-Policy = "geolocation=(self 'https://http5201-vite-assignment-neil-moras.netlify.app/'), microphone=(), camera=(), fullscreen=*"
